// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: agent.proto

package agent

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkerAgent_StartJob_FullMethodName = "/agent.WorkerAgent/StartJob"
)

// WorkerAgentClient is the client API for WorkerAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkerAgentClient interface {
	StartJob(ctx context.Context, in *JobRequest, opts ...grpc.CallOption) (*Ack, error)
}

type workerAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerAgentClient(cc grpc.ClientConnInterface) WorkerAgentClient {
	return &workerAgentClient{cc}
}

func (c *workerAgentClient) StartJob(ctx context.Context, in *JobRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, WorkerAgent_StartJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerAgentServer is the server API for WorkerAgent service.
// All implementations must embed UnimplementedWorkerAgentServer
// for forward compatibility.
type WorkerAgentServer interface {
	StartJob(context.Context, *JobRequest) (*Ack, error)
	mustEmbedUnimplementedWorkerAgentServer()
}

// UnimplementedWorkerAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkerAgentServer struct{}

func (UnimplementedWorkerAgentServer) StartJob(context.Context, *JobRequest) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartJob not implemented")
}
func (UnimplementedWorkerAgentServer) mustEmbedUnimplementedWorkerAgentServer() {}
func (UnimplementedWorkerAgentServer) testEmbeddedByValue()                     {}

// UnsafeWorkerAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerAgentServer will
// result in compilation errors.
type UnsafeWorkerAgentServer interface {
	mustEmbedUnimplementedWorkerAgentServer()
}

func RegisterWorkerAgentServer(s grpc.ServiceRegistrar, srv WorkerAgentServer) {
	// If the following call pancis, it indicates UnimplementedWorkerAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkerAgent_ServiceDesc, srv)
}

func _WorkerAgent_StartJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerAgentServer).StartJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerAgent_StartJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerAgentServer).StartJob(ctx, req.(*JobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkerAgent_ServiceDesc is the grpc.ServiceDesc for WorkerAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkerAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.WorkerAgent",
	HandlerType: (*WorkerAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartJob",
			Handler:    _WorkerAgent_StartJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent.proto",
}
